/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package amostraonline.frames;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.awt.*;
import java.io.IOException;

/**
 *
 * @author João Cláudio
 */
public class ObrasViniciusFrame extends javax.swing.JFrame {

    ImageIcon ImageUmaMulher = new ImageIcon(Toolkit.getDefaultToolkit().createImage(ImageIO.read(AutoursFrame.class.getResourceAsStream("/uma-mulher.png")).getSource()));
    ImageIcon ImageSoneto = new ImageIcon(Toolkit.getDefaultToolkit().createImage(ImageIO.read(AutoursFrame.class.getResourceAsStream("/soneto-separacao.png")).getSource()));
    ImageIcon ImageHiroshima = new ImageIcon(Toolkit.getDefaultToolkit().createImage(ImageIO.read(AutoursFrame.class.getResourceAsStream("/rosa-hiroshima.png")).getSource()));
    ImageIcon ImagePatria = new ImageIcon(Toolkit.getDefaultToolkit().createImage(ImageIO.read(AutoursFrame.class.getResourceAsStream("/patria-minha.png")).getSource()));
    ImageIcon ImageExegese = new ImageIcon(Toolkit.getDefaultToolkit().createImage(ImageIO.read(AutoursFrame.class.getResourceAsStream("/forma-exegese.png")).getSource()));
    ImageIcon ImageAriana = new ImageIcon(Toolkit.getDefaultToolkit().createImage(ImageIO.read(AutoursFrame.class.getResourceAsStream("/ariana-mulher.png")).getSource()));
    ImageIcon ImageElegias = new ImageIcon(Toolkit.getDefaultToolkit().createImage(ImageIO.read(AutoursFrame.class.getResourceAsStream("/cinco-elegias.png")).getSource()));
    ImageIcon ImageBalada = new ImageIcon(Toolkit.getDefaultToolkit().createImage(ImageIO.read(AutoursFrame.class.getResourceAsStream("/poema-balada.png")).getSource()));
    
    //Aqui está sendo criada objetos que são usados para representar uma imagem que será exibida na interface gráfica.
    
    public ObrasViniciusFrame() throws IOException {
        initComponents();
        this.setLocation(500,200); //Indica a localização que a janela será gerada
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Indica que quando o usuário fechar a janela, todos os processos serão finalizados
        this.setTitle("Principais obras de Vinicius de Moraes"); //Indica o título da janela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BotaoUmaMulher = new javax.swing.JButton();
        BotaoSonetoSeparacao = new javax.swing.JButton();
        BotaoRosaHiroshima = new javax.swing.JButton();
        BotaoPatriaMinha = new javax.swing.JButton();
        BotaoFormaExegese = new javax.swing.JButton();
        BotaoArianaMulher = new javax.swing.JButton();
        BotaoCincoElegias = new javax.swing.JButton();
        BotaoPoemasSonetosBaladas = new javax.swing.JButton();
        imagemObra = new javax.swing.JLabel();
        botaoVolta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"                                   Clique na setinha para ver a imagem da obra"},
                {"A uma mulher"},
                {"-----------------------------------------------------------------------------------------------------------"},
                {"Soneto de separação"},
                {"-----------------------------------------------------------------------------------------------------------"},
                {"A Rosa de Hiroshima"},
                {"-----------------------------------------------------------------------------------------------------------"},
                {"Pátria minha"},
                {"-----------------------------------------------------------------------------------------------------------"},
                {"Forma e exegese"},
                {"-----------------------------------------------------------------------------------------------------------"},
                {"Ariana, a mulher"},
                {"-----------------------------------------------------------------------------------------------------------"},
                {"Cinco elegias"},
                {"-----------------------------------------------------------------------------------------------------------"},
                {"Poemas, sonetos e baladas"},
                {"-----------------------------------------------------------------------------------------------------------"}
            },
            new String [] {
                "Principais obras de Vinicius de Moraes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BotaoUmaMulher.setText("->");
        BotaoUmaMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoUmaMulherActionPerformed(evt);
            }
        });

        BotaoSonetoSeparacao.setText("->");
        BotaoSonetoSeparacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSonetoSeparacaoActionPerformed(evt);
            }
        });

        BotaoRosaHiroshima.setText("->");
        BotaoRosaHiroshima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRosaHiroshimaActionPerformed(evt);
            }
        });

        BotaoPatriaMinha.setText("->");
        BotaoPatriaMinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPatriaMinhaActionPerformed(evt);
            }
        });

        BotaoFormaExegese.setText("->");
        BotaoFormaExegese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFormaExegeseActionPerformed(evt);
            }
        });

        BotaoArianaMulher.setText("->");
        BotaoArianaMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoArianaMulherActionPerformed(evt);
            }
        });

        BotaoCincoElegias.setText("->");
        BotaoCincoElegias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCincoElegiasActionPerformed(evt);
            }
        });

        BotaoPoemasSonetosBaladas.setText("->");
        BotaoPoemasSonetosBaladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPoemasSonetosBaladasActionPerformed(evt);
            }
        });

        imagemObra.setText("");

        botaoVolta.setText("Voltar");
        botaoVolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(botaoVolta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoUmaMulher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoSonetoSeparacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoRosaHiroshima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoPatriaMinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoFormaExegese, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoArianaMulher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoCincoElegias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoPoemasSonetosBaladas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(imagemObra, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(BotaoUmaMulher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoSonetoSeparacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoRosaHiroshima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoPatriaMinha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoFormaExegese)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoArianaMulher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoCincoElegias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoPoemasSonetosBaladas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imagemObra, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addComponent(botaoVolta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltaActionPerformed
        try {
            new SaibaViniciusFrame().setVisible(true);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        dispose();
        
        //Quando o botão voltar for acionado, uma nova janela será criada e a janela apresentada para o usuário será finalizada
    }//GEN-LAST:event_botaoVoltaActionPerformed

    private void BotaoUmaMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoUmaMulherActionPerformed
        imagemObra.setIcon(ImageUmaMulher); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_BotaoUmaMulherActionPerformed

    private void BotaoSonetoSeparacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSonetoSeparacaoActionPerformed
        imagemObra.setIcon(ImageSoneto); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_BotaoSonetoSeparacaoActionPerformed

    private void BotaoRosaHiroshimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRosaHiroshimaActionPerformed
        imagemObra.setIcon(ImageHiroshima); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_BotaoRosaHiroshimaActionPerformed

    private void BotaoPatriaMinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPatriaMinhaActionPerformed
        imagemObra.setIcon(ImagePatria); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_BotaoPatriaMinhaActionPerformed

    private void BotaoFormaExegeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFormaExegeseActionPerformed
        imagemObra.setIcon(ImageExegese); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_BotaoFormaExegeseActionPerformed

    private void BotaoArianaMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoArianaMulherActionPerformed
        imagemObra.setIcon(ImageAriana); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_BotaoArianaMulherActionPerformed

    private void BotaoCincoElegiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCincoElegiasActionPerformed
        imagemObra.setIcon(ImageElegias); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_BotaoCincoElegiasActionPerformed

    private void BotaoPoemasSonetosBaladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPoemasSonetosBaladasActionPerformed
        imagemObra.setIcon(ImageBalada); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_BotaoPoemasSonetosBaladasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObrasViniciusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObrasViniciusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObrasViniciusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObrasViniciusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ObrasViniciusFrame().setVisible(true);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoArianaMulher;
    private javax.swing.JButton BotaoCincoElegias;
    private javax.swing.JButton BotaoFormaExegese;
    private javax.swing.JButton BotaoPatriaMinha;
    private javax.swing.JButton BotaoPoemasSonetosBaladas;
    private javax.swing.JButton BotaoRosaHiroshima;
    private javax.swing.JButton BotaoSonetoSeparacao;
    private javax.swing.JButton BotaoUmaMulher;
    private javax.swing.JButton botaoVolta;
    private javax.swing.JLabel imagemObra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
