/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package amostraonline.frames;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author João Cláudio
 */
public class ObrasCarlosFrame extends javax.swing.JFrame {

    ImageIcon ImageContosdeAprendiz = new ImageIcon("contos-de-aprendiz.png");
    ImageIcon ImageBocadeLuar = new ImageIcon("boca-de-luar.png");
    ImageIcon ImageRosadoPovo = new ImageIcon("a-rosa-do-povo.png");
    ImageIcon ImageSentimentodoMundo = new ImageIcon("Sentimento-no-mundo.png");
    ImageIcon ImageAntologiaPoetica = new ImageIcon("Antologia-poetica.png");
    ImageIcon ImageBolsaeaVida = new ImageIcon("a-bolsa-e-a-vida.png");
    ImageIcon ImageCadeiraBalanco = new ImageIcon("cadeira-de-balanco.png");
    ImageIcon ImageAmarAprendeAmando = new ImageIcon("amar-se-aprende-amando.png");
    
    //Aqui está sendo criada objetos que são usados para representar uma imagem que será exibida na interface gráfica.
    
    
    public ObrasCarlosFrame() {
        initComponents();
        this.setLocation(500,200); //Indica a localização que a janela será gerada
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Indica que quando o usuário fechar a janela, todos os processos serão finalizados
        this.setTitle("Obras de Carlos Drummond de Andrade"); //Indica o título da janela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botaoContodeAprendiz = new javax.swing.JToggleButton();
        imagemObra = new javax.swing.JLabel();
        botaoBocadeLuar = new javax.swing.JButton();
        botaoRosadoPovo = new javax.swing.JButton();
        botaoSentimentodoMundo = new javax.swing.JButton();
        botaoAntologiaPoetica = new javax.swing.JButton();
        botaoBolsaeaVida = new javax.swing.JButton();
        botaoCadeiradeBalanco = new javax.swing.JButton();
        botaoAmarAprendeAmando = new javax.swing.JButton();
        botaoVoltarObras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"                                   Clique na setinha para ver a imagem da obra"},
                {"Contos de aprendiz"},
                {"---------------------------------------------------------------------------------------------------"},
                {"Boca de luar"},
                {"---------------------------------------------------------------------------------------------------"},
                {"A rosa do povo"},
                {"---------------------------------------------------------------------------------------------------"},
                {"Sentimento do mundo"},
                {"---------------------------------------------------------------------------------------------------"},
                {" Antologia poética"},
                {"---------------------------------------------------------------------------------------------------"},
                {"A bolsa e a vida"},
                {"---------------------------------------------------------------------------------------------------"},
                {"Cadeira de balanço"},
                {"---------------------------------------------------------------------------------------------------"},
                {"Amar se aprende amando"},
                {"---------------------------------------------------------------------------------------------------"}
            },
            new String [] {
                "Obras de Carlos Drummond"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        botaoContodeAprendiz.setText("->");
        botaoContodeAprendiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoContodeAprendizActionPerformed(evt);
            }
        });

        imagemObra.setText("|");

        botaoBocadeLuar.setText("->");
        botaoBocadeLuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBocadeLuarActionPerformed(evt);
            }
        });

        botaoRosadoPovo.setText("->");
        botaoRosadoPovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRosadoPovoActionPerformed(evt);
            }
        });

        botaoSentimentodoMundo.setText("->");
        botaoSentimentodoMundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSentimentodoMundoActionPerformed(evt);
            }
        });

        botaoAntologiaPoetica.setText("->");
        botaoAntologiaPoetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAntologiaPoeticaActionPerformed(evt);
            }
        });

        botaoBolsaeaVida.setText("->");
        botaoBolsaeaVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBolsaeaVidaActionPerformed(evt);
            }
        });

        botaoCadeiradeBalanco.setText("->");
        botaoCadeiradeBalanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadeiradeBalancoActionPerformed(evt);
            }
        });

        botaoAmarAprendeAmando.setText("->");
        botaoAmarAprendeAmando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAmarAprendeAmandoActionPerformed(evt);
            }
        });

        botaoVoltarObras.setText("Voltar");
        botaoVoltarObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarObrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoContodeAprendiz, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(botaoBocadeLuar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoRosadoPovo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoSentimentodoMundo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoAntologiaPoetica, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoBolsaeaVida, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoCadeiradeBalanco, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoAmarAprendeAmando, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagemObra, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(botaoVoltarObras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoContodeAprendiz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoBocadeLuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRosadoPovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSentimentodoMundo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAntologiaPoetica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoBolsaeaVida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadeiradeBalanco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAmarAprendeAmando))
                    .addComponent(imagemObra, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(botaoVoltarObras)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoContodeAprendizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoContodeAprendizActionPerformed
        imagemObra.setIcon(ImageContosdeAprendiz); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_botaoContodeAprendizActionPerformed

    private void botaoBocadeLuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBocadeLuarActionPerformed
        imagemObra.setIcon(ImageBocadeLuar); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_botaoBocadeLuarActionPerformed

    private void botaoRosadoPovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRosadoPovoActionPerformed
        imagemObra.setIcon(ImageRosadoPovo); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_botaoRosadoPovoActionPerformed

    private void botaoSentimentodoMundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSentimentodoMundoActionPerformed
        imagemObra.setIcon(ImageSentimentodoMundo); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_botaoSentimentodoMundoActionPerformed

    private void botaoAntologiaPoeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAntologiaPoeticaActionPerformed
        imagemObra.setIcon(ImageAntologiaPoetica); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_botaoAntologiaPoeticaActionPerformed

    private void botaoBolsaeaVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBolsaeaVidaActionPerformed
        imagemObra.setIcon(ImageBolsaeaVida); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_botaoBolsaeaVidaActionPerformed

    private void botaoCadeiradeBalancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadeiradeBalancoActionPerformed
        imagemObra.setIcon(ImageCadeiraBalanco); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_botaoCadeiradeBalancoActionPerformed

    private void botaoAmarAprendeAmandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAmarAprendeAmandoActionPerformed
        imagemObra.setIcon(ImageAmarAprendeAmando); //Aqui estamos indicando ao JLabel que uma imagem será gerada ao apertar o botão
    }//GEN-LAST:event_botaoAmarAprendeAmandoActionPerformed

    private void botaoVoltarObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarObrasActionPerformed
        new SaibaCarlosFrame().setVisible(true);
        dispose();
        
        //Quando o botão voltar for acionado, uma nova janela será criada e a janela apresentada para o usuário será finalizada
    }//GEN-LAST:event_botaoVoltarObrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObrasCarlosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObrasCarlosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObrasCarlosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObrasCarlosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObrasCarlosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAmarAprendeAmando;
    private javax.swing.JButton botaoAntologiaPoetica;
    private javax.swing.JButton botaoBocadeLuar;
    private javax.swing.JButton botaoBolsaeaVida;
    private javax.swing.JButton botaoCadeiradeBalanco;
    private javax.swing.JToggleButton botaoContodeAprendiz;
    private javax.swing.JButton botaoRosadoPovo;
    private javax.swing.JButton botaoSentimentodoMundo;
    private javax.swing.JButton botaoVoltarObras;
    private javax.swing.JLabel imagemObra;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
